# Generated by Django 6.0.4 on 2026-04-26 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "city",
                "verbose_name_plural": "cities",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=128)),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("root_password_secret", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unknown", "unknown"),
                            ("online", "online"),
                            ("offline", "offline"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hosts",
                        to="host.city",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PasswordChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password_secret", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_logs",
                        to="host.host",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ServerRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("remark", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="host.city",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("city", "name")},
            },
        ),
        migrations.AddField(
            model_name="host",
            name="server_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hosts",
                to="host.serverroom",
            ),
        ),
        migrations.CreateModel(
            name="HostCountStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stat_date", models.DateField()),
                ("host_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="host.city"
                    ),
                ),
                (
                    "server_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="host.serverroom",
                    ),
                ),
            ],
            options={
                "ordering": ["-stat_date", "city_id", "server_room_id"],
                "unique_together": {("stat_date", "city", "server_room")},
            },
        ),
    ]
